### ISSUE TITLE
Error on client login() method: Uncaught Error: Invalid keysWithString value

### ISSUE THREAD

**Issue by simentesempre** [directus/sdk-js#102]
# 🐞 bug report

### Is this a regression?
I don't know

### Description
on client's login() method i got the following error

Uncaught Error: Invalid keysWithString value: {"url":"http://project.fenic:3000/","project":"_"}

## 🔬 Minimal Reproduction
This is built in a React custom hook, inside a useEffect hook
```ts
import DirectusSDK from '@directus/sdk-js'
...
const api_endpoint = `${process.env.REACT_APP_API_ENDPOINT_PATH}`
...
const client = new DirectusSDK()
client.login({
    url: api_endpoint,
    project: "_"
})
```

## 🔥 Exception or Error
<pre><code>

Uncaught Error: Invalid keysWithString value: {"url":"http://project.fenic:3000/","project":"_"}
Argument Name: credentials
Keys: email, password

</code></pre>

## 🌍 Your Environment

**SDK Version:** ```latest```
Node version 10.16.0

**Anything else relevant?**
This is built in a React custom hook, inside a useEffect hook

**Comment by simentesempre** [comment]
I realized my mistake, sorry

**Comment by rijkvanzanten** [comment]
What was it @simentesempre? In case someone else runs into the same issue :)

**Comment by simentesempre** [comment]
I'm sorry, the mistake was using the login() method itself, since I wasn't "actually" logging in. So I fixed it just like this: 
`const client = new DirectusSDK({
    url: api_endpoint,
    project: "_"
})`
Hope it helps
