### ISSUE TITLE
403 forbidden when calling getCollections after client.login

### ISSUE THREAD

**Issue by djnuller** [directus/sdk-js#103]
I tried out directus right after installation and added 2 collections. 
Posts
Movies

**System**
Ubuntu 18.04.3 LTS
PHP 7.2
Apache2 : LoadModule php7_module /usr/lib/apache2/modules/libphp7.2.so
mysql 5.7.27-0ubuntu0.18.04.1

**Service code** 
import DirectusSDK from "@directus/sdk-js";

const client = new DirectusSDK();

client.login({
    url: "http://***/directus/public",
    project: "_",
    email: "ADMIN EMAIL",
    password: "ADMIN PASSWORD",
    persist: true
  });

export const getPosts = () => {
    client.getCollections()
    .then(data => {
        console.log(data);
    })
    .catch(error => console.error(error));

>

I'm getting 401, if inserting wrong username/password. 
But with right username/password I get a 403.

**Stacktrace**
`[2019-09-01 00:29:12] api[_].ERROR: Directus\Permissions\Exception\ForbiddenCollectionReadException: Reading items from "directus_collections" collection was denied in /var/www/html/directus/src/core/Directus/Permissions/Acl.php:988
Stack trace:
#0 /var/www/html/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(1152): Directus\Permissions\Acl->enforceReadOnce
directus/app#1 /var/www/html/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1136): Directus\Database\TableGateway\BaseTableGateway->enforceReadPermission
directus/app#2 /var/www/html/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1258): Directus\Database\TableGateway\RelationalTableGateway->fetchItems
directus/app#3 /var/www/html/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(854): Directus\Database\TableGateway\RelationalTableGateway->fetchData
directus/app#4 /var/www/html/directus/src/core/Directus/Services/TablesService.php(68): Directus\Database\TableGateway\RelationalTableGateway->getItems
directus/app#5 /var/www/html/directus/src/endpoints/Collections.php(58): Directus\Services\TablesService->findAll
directus/app#6 [internal function]: Directus\Api\Routes\Collections->all
directus/app#7 /var/www/html/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
directus/app#8 /var/www/html/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
directus/app#9 /var/www/html/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
directus/app#10 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/app#11 /var/www/html/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#12 [internal function]: Slim\DeferredCallable->__invoke
directus/app#13 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#14 /var/www/html/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(120): Slim\Route->Slim\{closure}
directus/app#15 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
directus/app#16 /var/www/html/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#17 [internal function]: Slim\DeferredCallable->__invoke
directus/app#18 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#19 /var/www/html/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
directus/app#20 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
directus/app#21 /var/www/html/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#22 [internal function]: Slim\DeferredCallable->__invoke
directus/app#23 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#24 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
directus/app#25 /var/www/html/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
directus/app#26 /var/www/html/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
directus/app#27 /var/www/html/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
directus/app#28 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/app#29 /var/www/html/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#30 [internal function]: Slim\DeferredCallable->__invoke
directus/app#31 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#32 /var/www/html/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
directus/app#33 /var/www/html/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
directus/app#34 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
directus/app#35 /var/www/html/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#36 [internal function]: Slim\DeferredCallable->__invoke
directus/app#37 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#38 /var/www/html/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
directus/app#39 [internal function]: RKA\Middleware\IpAddress->__invoke
directus/app#40 /var/www/html/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#41 [internal function]: Slim\DeferredCallable->__invoke
directus/app#42 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#43 /var/www/html/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
directus/app#44 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus/app#45 /var/www/html/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#46 [internal function]: Slim\DeferredCallable->__invoke
directus/app#47 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#48 /var/www/html/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure}
directus/app#49 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
directus/app#50 /var/www/html/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#51 [internal function]: Slim\DeferredCallable->__invoke
directus/app#52 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#53 /var/www/html/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus/app#54 /var/www/html/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus/app#55 /var/www/html/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus/app#56 /var/www/html/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
directus/app#57 /var/www/html/directus/public/index.php(5): Directus\Application\Application->run [] []`

**Comment by rijkvanzanten** [comment]
`client.login` is (like every other method) asynchronous. You should wait until that's done before trying to call `getCollections`, as the client won't be logged in yet

**Comment by djnuller** [comment]
The problem also accures when calling it directly through postman or insomnia.
