### ISSUE TITLE
how can i filter null field?

### ISSUE THREAD

**Issue by mustafa220** [directus/sdk-js#105]
hi

i want to get my items by null field

i tried this code, but didnt work.

can you help me please?

```
const menu = await client.getItems("menu", {
					fields:"*.*",
					filters:{
						topmenu:null
					}
				});
```

**Comment by rijkvanzanten** [comment]
Try

```js
await client.getItems('menu', {
  fields: '*.*',
  filter: {
    topmenu: {
      null: true
    }
  }
});
```

**Comment by mustafa220** [comment]
@rijkvanzanten  still dont work.

im getting this response

![image](https://user-images.githubusercontent.com/9257902/65123612-4a1e5a80-d9fc-11e9-9efb-a14de3e97a0b.png)
