### ISSUE TITLE
[Question] Licensing and usage

### ISSUE THREAD

**Issue by LouizFC** [directus/sdk-js#115]
Greetings.

For what I understand about GPL licensing, if I am to use this SDK on a private project, I will need to serve my source code to the users.

If I am to use the code on the server side, it is ok, because the definition of "distribution" on the GPL license is permissive enough to not force me to distribute sources as long as the code is used only on the server (thats why AGPL exists, to be less permissive).

But if I am serving this in the client side, I must serve all the sources of my client side application, because it does count as "distribution" on the license. So I will need to serve all config files and all un-minified and un-transformed source files.

Is this intentional or something that got overlooked?

**Comment by benhaynes** [comment]
@rijkvanzanten — Thoughts on using an MIT license (or something more permissible than GPLv3) to avoid confusion?

https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60

> 5. If you dare build your business solely from this code, you risk open-sourcing the whole code base.

https://opensource.stackexchange.com/questions/4360/what-are-the-implications-of-licensing-a-javascript-library-under-gpl

**Comment by rijkvanzanten** [comment]
Good point! I originally added the GPL-3.0 license because the Directus API / app are licensed as such. There's no reason not to make the SDK MIT

**Comment by rijkvanzanten** [comment]
Changed it! (v6.0.0-alpha.6 and up is MIT licensed)
