### ISSUE TITLE
Undefined exception

### ISSUE THREAD

**Issue by westhouseit** [directus/sdk-js#116]
# 🐞 Bug report

### Is this a regression?
Unknown

### Description

See: https://github.com/Jonesus/gatsby-source-directus7/issues/18

Seems that the SDK isn't returning an exception when failing on the get() method, though I could be wrong.

## 🔬 Minimal Reproduction
```ts
try {
  // Directus SDK doesn't yet support fetching files via a
  // dedicated method yet but this works just as well
  const filesData = await this.client.get('files', { limit: '-1' });
  return filesData.data;
} catch (e) {
  error('gatsby-source-directus: Error while fetching files: ', e);
  return [];
}
```

## 🔥 Exception or Error
<pre><code>
GSD7: error gatsby-source-directus: Error while fetching files: undefined
</code></pre>

The key is the **undefined** being returned.

## 🌍 Your Environment

**SDK Version:** ```v5.3.1```
Also tried with 5.3.4 and no change.

**Anything else relevant?**

**Comment by rijkvanzanten** [comment]
I just tried your minimal reproduction, but it seems to be working fine on my end (no Gatsby, just JS):

```javascript
const client = new DirectusSDK({
        url: 'http://localhost:3100',
        token: 'gKLP9p'
});

// Attempt to fetch files
client.get('files', { limit: '-1' })
        .then(console.log)
        .catch(console.log);

// Should return 404
client.get('non-existing')
        .then(console.log)
        .catch(console.log);
```

The files get returned correctly, and the 404 is being caught in the `.catch`..

Could it be that your API is failing somewhere earlier? Maybe the CORS headers cause trouble before the SDK even gets the chance to catch the error?

**Comment by westhouseit** [comment]
Hmm... thanks, will look into this is in more depth.

**Comment by tfasolino-crak** [comment]
Same problem here

**Comment by rijkvanzanten** [comment]
@tfasolino-crak yikes.. Unless we figure out how to consistently reproduce it, there's not much I can do..

**Comment by tfasolino-crak** [comment]
> @tfasolino-crak yikes.. Unless we figure out how to consistently reproduce it, there's not much I can do..

I' m still looking for the problem. I will give you feedback about this

**Comment by tfasolino-crak** [comment]
Ok for my problem, it was a database cache problem...The sdk returns an 'undefined' for some specific cases, it could be a problem for some people. So it was not a problem with the sdk :)
Thx for your answer and great plugin
