### ISSUE TITLE
LoggedIn State in latest beta

### ISSUE THREAD

**Issue by gianniskarmas** [directus/sdk-js#121]
LoggedIn State has been removed in latest betas.
What is the best way to check if user is logged in?

**Comment by rijkvanzanten** [comment]
The JS SDK can't read the logged in state if you're using cookies to authenticate. I might re-add it as a async method that will return the token state if JWTs are used or do a request to verify the cookie. As for now, fetching the project info is the cheapest way to check if your session is active

**Comment by gianniskarmas** [comment]
Sorry for continuing this here but cookie is not documented.
Tried to use it like:
`project: "api",
 persist: true,
 storage: 'cookie'`
but no cookie is being created.
Can you please explain.

**Comment by rijkvanzanten** [comment]
The cookie is set to httpOnly so it can't be read from JavaScript at all. This is done by design, as it's the only way to protect the key from being accessible by XSS attacks. 

Performing any query and checking the result for either 200 or 401 is the only way to really check if the cookie is still attached to a valid session. Generally speaking, the cookie session won't end until you explicitly kill it through the api, as the cookie will be refreshed when the api is used.

As for JWTs, the payload of the JWT can be read from JS. There is a getPayload function that is exported from the SDK. The token itself is a regular JWT, so you can also use any other JWT library to read the payload

**Comment by gianniskarmas** [comment]
Thank you for the explanation.
Can you also please add the 'loggedIn' call in the next npm update?
It is very useful for 'isAuthenticated' functions within an app.

**Comment by rijkvanzanten** [comment]
Yeah! I'll add a `isLoggedIn()` method that handles the logic between JWT and cookies under the hood. It will be asynchronous, so usage would be:

```js
const loggedIn = await client.isLoggedIn();
```

**Comment by ahmtaras** [comment]
> Yeah! I'll add a `isLoggedIn()` method that handles the logic between JWT and cookies under the hood. It will be asynchronous, so usage would be:
> 
> ```js
> const loggedIn = await client.isLoggedIn();
> ```

this function always returns true. Am I doing something wrong?

**Comment by rijkvanzanten** [comment]
Are you sure you're not logged in? The function itself lgtm:

https://github.com/directus/sdk-js/blob/3f1eef39569980787155e95811ca476621b065f5/src/SDK.ts#L884-L896

**Comment by ahmtaras** [comment]
No login. The result is returned true;
![Adsız](https://user-images.githubusercontent.com/23402407/72934678-1cb03780-3d75-11ea-85f8-247bb224b4b3.png)

I have successfully logged in.
![Adsız](https://user-images.githubusercontent.com/23402407/72934779-4bc6a900-3d75-11ea-85de-6697bee46459.png)

Again, the result is correct
![Adsız](https://user-images.githubusercontent.com/23402407/72934936-8a5c6380-3d75-11ea-8b63-e7682fbb99b8.png)

**Comment by ahmtaras** [comment]
@rijkvanzanten 
The reason for this is; 

`res.data.public === undefined` instead `res.public === undefined` you should use.

![Adsız](https://user-images.githubusercontent.com/23402407/72939485-035fb900-3d7e-11ea-8950-80d29f94523b.png)

**Comment by rijkvanzanten** [comment]
Good catch! Wanna open a PR for that?

**Comment by ahmtaras** [comment]
> Good catch! Wanna open a PR for that?

I can post an edit. If we just change that part, the problem will be solved. You can do it too.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/sdk-js/pull/133

**Comment by gianniskarmas** [comment]
So how do I get client details after a refresh using cookie mode?
Using nuxt and in store I use:
`export const actions = {
    async nuxtServerInit ({ commit }) {
        commit('setAuth', await this.$directus.isLoggedIn());
`
that seems to resolve in an empty object.
What is the best way to get logged in user's data on a refresh?

**Comment by rijkvanzanten** [comment]
@gianniskarmas You can use the `getMe` method to retrieve the current user. If that method throws a 404 error, it's safe to assume you're not logged in

**Comment by michapixel** [comment]
> 
> 
> @gianniskarmas You can use the `getMe` method to retrieve the current user. If that method throws a 404 error, you're not logged in

shouldn't that return 403?

**Comment by rijkvanzanten** [comment]
@michapixel depends on how you see the request. 

If you're not logged in, there is no "me" to be found, so a resource not found feels appropriate to me too.
