### ISSUE TITLE
V6 not working in node.js

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/sdk-js#125]
When I use the newest version in a node.js process (gatsby-node), I get and `TypeError: DirectusSDK is not a constructur` error.

This is how I implement it:
```
const DirectusSDK = require('@directus/sdk-js');

const client = new DirectusSDK({
  url: apiCredentials.url,
  project: apiCredentials.project,
});
```

**Comment by pgegenfurtner** [comment]
Importing the sdk via `const DirectusSDK = require('@directus/sdk-js').default;`works

**Comment by shealavington** [comment]
I did have a similar issue here @rijkvanzanten - I couldn't import the CDN in JSFiddle and just start playing...

https://unpkg.com/@directus/sdk-js@6.0.0/dist/umd/directus-sdk.min.js

I had to go back to 5.* or something.

**Comment by rijkvanzanten** [comment]
@shealavington v6 exports the SDK directly:

```js
const { SDK } = DirectusSDK;

this.directus = new SDK({
  etc
});
```
