### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">=8.0.0 <13.0.0". Got "13.2.0"

### ISSUE THREAD

**Issue by floyd0987** [directus/sdk-js#129]
when adding directus with yarn, I get the following error

yarn add @directus/sdk-js

yarn add v1.19.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @directus/sdk-js@6.0.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0 <13.0.0". Got "13.2.0"
error Found incompatible module.

**Comment by rijkvanzanten** [comment]
Well, the error says it all. The SDK requires you to use a version of node between 8+ and <13, and you're on 13.2. I haven't had the time to test the SDK on node 13+ yet. I can remove the engine check, but that leaves no guarantee that it will actually work on the newest version of node.
