### ISSUE TITLE
Requests fail when using Cloudfront with Directus

### ISSUE THREAD

**Issue by juliosouza-pushstart** [directus/sdk-js#132]
# 🐞 Bug report

### Is this a regression?
Not sure.

### Description
When using the Directus instance behind Cloudfront, GET requests fail due an incorrect Content-length header.

Specifically, API.request forces an empty `data` property to the options object passed to `this.xhr.request(requestOptions)`, even in GET requests, which shouldn't have any content.

**I've tried removing the default value of the `data` function param and it does work as expected.**

## 🔬 Minimal Reproduction
This was observed when using the [official Gatsby plugin](https://github.com/directus/gatsby-source), with a standard configuration of Cloudfront.

## 🌍 Your Environment

**SDK Version:** ```v6.0.0```

**Anything else relevant?**

...

**Comment by rijkvanzanten** [comment]
Want to add a PR for that @juliosouza-pushstart ? 🙂

**Comment by juliosouza-pushstart** [comment]
@rijkvanzanten I'm not sure how to setup the dev environment, and I don't feel safe editing the typescript code without checking it.

I'd be fine if you do it instead. Thanks!

**Comment by rijkvanzanten** [comment]
I don't really have the time to prioritize this now.. that's why 😬

**Comment by JulioC** [comment]
@juliosouza-pushstart here. I've created a PR with the proposed fix
