### ISSUE TITLE
Calls of getCollectionRelations failing

### ISSUE THREAD

**Issue by realpasha** [directus/sdk-js#160]
# 🐞 Bug report
Using the SDK's call `getCollectionRelations(collection, params = {})` fails, because the naming of the attributes in the relations table has changed:
`collection_a` -> `collection_many`
`collection_b` -> `collection_one`

_(I could not verify the directus api version, when the naming of these attributes was changed in the relations table)_

## 🔬 Minimal Reproduction
```
import SDK from '@directus/sdk-js';

const sdk = new SDK({...});

try {
    let upload = await sdk.getCollectionRelations('mycollection');
} catch (e) {
    console.log(e)
}
```

## 🔥 Exception or Error

_**API Calls & Responses**_
__
_http://example.com/_/relations?filter[collection_a][eq]=mycollection_
```
{"error":{"code":202,"message":"Invalid field \"collection_a\" in \"directus_relations\"","class":"Directus\\Database\\Exception\\InvalidFieldException","file":"C:\\Projects\\www\\slimpage\\DirectusSuite\\src\\core\\Directus\\Database\\TableGateway\\RelationalTableGateway.php","line":1502}}
```
_http://example.com/_/relations?filter[collection_b][eq]=mycollection_
```
{"error":{"code":202,"message":"Invalid field \"collection_b\" in \"directus_relations\"","class":"Directus\\Database\\Exception\\InvalidFieldException","file":"C:\\Projects\\www\\slimpage\\DirectusSuite\\src\\core\\Directus\\Database\\TableGateway\\RelationalTableGateway.php","line":1502}}
```

## 🌍 Your Environment
SDK Version: v6.0.5
Directus Suite Version: v8.6.2

**Comment by rijkvanzanten** [comment]
Fixed in #161
