### ISSUE TITLE
File Upload (bad baseUrl)

### ISSUE THREAD

**Issue by nathannau** [directus/sdk-js#172]
When uploading file the request go to bad host.

File SDK.ts (434)
```php
return this.api.xhr.post(`${this.config.url}/${this.config.project}/files`, data, {
```
if is like : 
` config = { url:'/', project:'toto' } `
the request will be :
`...post('//toto/files', data, {...`

Rolve : 
Prefer use `this.api.post` in place of `this.api.xhr.post`

**Comment by rijkvanzanten** [comment]
Fixed in #173
