### ISSUE TITLE
No method for reset password

### ISSUE THREAD

**Issue by jigneshbhavani** [directus/sdk-js#174]
I'm trying to reset the password for directus_users. I checked the documentation and sdk as well but I couldn't find the method for resetting the password after requesting the token.
`client.requestPasswordReset(email)` used to request the token.

There should be another method for resetting the password such as.
`client.resetPassword(params);` that accept the token, password parameters and uses Endpoint : `POST /:project/auth/password/reset `

Any thoughts?

**Comment by rijkvanzanten** [comment]
That makes sense, however, the `requestPasswordReset` method sends an email to the user with a link to the app, so when you're using the SDK, there's no way of getting that token in the first place is there?

**Comment by pgegenfurtner** [comment]
@rijkvanzanten yes there is. Couple weeks ago I implemented an option to send an optional reset_url with the `requestPasswordReset`. That way you would get the token and could use a `resetPassword` method (https://docs.directus.io/api/authentication.html#request-a-password-reset)

**Comment by rijkvanzanten** [comment]
Ahh you're absolutely right @pgegenfurtner!

**Comment by jigneshbhavani** [comment]
@pgegenfurtner Exactly! In that case, Directus SDK users can use the `resetPassword` method. Mobile application users can also be able to use deep-link to reset the password in app. 
@rijkvanzanten  Appreciate if you consider this request for a new method in SDK.

**Comment by rijkvanzanten** [comment]
@jigneshbhavani do you wanna open a PR to add this in?

**Comment by pgegenfurtner** [comment]
I've made a PR which adds this method
