### ISSUE TITLE
Nested parameters fail

### ISSUE THREAD

**Issue by gielcobben** [directus/sdk-js#26]
Hello there,

How do I rewrite the [get parameters](https://api.getdirectus.com/1.1/#Get_Parameters) with this javascript sdk? I'm not sure how I can get every tag where `slug` equals `hello` or `world` for example. 

I tried something like this:

```js
  const items = await directus.getItems("tags", {
    columns: "title,slug",
    filters: {
      slug: {
        eq: "hello,world"
      },
    },
  });
```

Thanks,

Giel

**Comment by rijkvanzanten** [comment]
Hey @gielcobben!


This has been requested before in https://github.com/directus/directus-sdk-javascript/issues/19, and as far as I know should've been implemented in https://github.com/directus/directus-sdk-javascript/commit/67d28777ebd93ec133961178e623ce7685f4894a.. However, it seems like the `qs` library doesn't support multilevel queries! 😟

https://github.com/sindresorhus/query-string#nesting

A quick and dirty fix for now would be using it like this:

```js
  const items = await directus.getItems("tags", {
    columns: "title,slug",
    filters: {
      "slug[eq]": "hello,world",
    },
  });
```

Not pretty, but does the job for now

**Comment by gielcobben** [comment]
hmm I get this error: `Request failed with status code 500`.

**Comment by rijkvanzanten** [comment]
Ohh oops, this will transform into `filters[slug[eq]]=hello,world`.. sorry ‘bout that. Writing the full thing at the top level should do it..

```js
const items = await directus.getItems("tags", {
    columns: "title,slug",
    "filters[slug][eq]": "hello,world",
  });
```

**Comment by rijkvanzanten** [comment]
Let’s find out if there’s a good alternative of qs which does supported this style of nesting.

**Comment by rijkvanzanten** [comment]
This syntax is now supported:

```js
client.getItems("movies", {
  filter: {
    name: {
      eq: "test"
    }
  }
});
```

**Comment by coatesap** [comment]
Has this started failing again? On the latest version of Axios (0.19.0) making post requests works as expected, but get requests end up getting encoded.

Params:
![image](https://user-images.githubusercontent.com/1926626/63152111-f090cd80-c002-11e9-9b6f-7d7c97f2c2f4.png)

Post request:
![image](https://user-images.githubusercontent.com/1926626/63152008-b9bab780-c002-11e9-8d22-56465f93a529.png)

Get request:
![image](https://user-images.githubusercontent.com/1926626/63152062-d6ef8600-c002-11e9-8314-6041fcaa24e6.png)

**Comment by rijkvanzanten** [comment]
The structure of the parameter is

```
{
  filter: {
    name: {
      eg: "value"
    }
  }
}
```

Besides, `endsWith` and `startsWith` aren't valid Directus filter parameters:

https://docs.directus.io/api/reference.html#filtering

**Comment by coatesap** [comment]
@rijkvanzanten - apologies - I was hopping between this issue and another closely related Axios issue in different browser tabs. I'll delete my comment shortly.

**Comment by pachiraDIG** [comment]
Having trouble with getting structure correct for filtering "future events" :
```
client.getItems("events", {
  filters: {
    date: {
      gt: "now"
    }
  }
})
```
Have also tried replacing `"now"` with a formatted a javascript date :
```
const now = new Date().toJSON().replace('T', ' ').split('.')[0];
// 2020-01-03 22:58:24
```
but no luck.

Any suggestions?

Thanks!

**Comment by rijkvanzanten** [comment]
I'm assuming yes, but does this collection have a `date` field? Also, does it work if you open it directly from the API? `/items/events?filter[date][gt]=2020-01-03`?
