### ISSUE TITLE
client.getMe() not working after client.login() using `mode: cookie` in a NodeJS Environment.

### ISSUE THREAD

**Issue by Demonicious** [directus/sdk-js#270]
I've set up a Directus Project (localhost) and to consume my API on my application, I'm using the Directus SDK in a NodeJS Application.

**Im using Sapper, which is a Framework like Next.js** 
In Sapper the `export/import` syntax works and is converted into normal `const module = require('mod')` syntax when you build the server, So that should not be an issue. Also note that the code im showing is strictly server-side to remove any misconceptions as Sapper also has client-sided routes.

So I have a file which exports a `new DirectusSDK` from `Client.js`:
```js
import DirectusSDK from "@directus/sdk-js";
import { api } from "./../Config/app";

const client = new DirectusSDK({
    url: api.base,
    project: 'xhhzy',
    mode: "cookie",
    persist: true
});

export default client;
```

Next, I'm importing this Client and Logging in using an E-Mail and Password:
```js
import client from "App/Modules/Directus";

export async function post(req, res) {
    // Parameter Validation and such...
    client.login({
        email: user.email,
        password: user.password,
        mode: 'cookie',
        persist: true
    }).then(response => {
        res.json(response.data.user);
    }).catch(e => {
        // Error code checking, displaying message and such...
    });
}
```
This all works, and I'm successfully obtaining the user and can work with the user's profile. But If I call `client.getMe()` inside the `.then()` Promise Handler or from a Different Route:
```js
import client from "App/Modules/Directus";

export async function get(req, res) {
    let response = await client.getMe();

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(response));
}
```

This does not work and results in a `Unauthorized Request` error.

Any help / suggestions with this would be really appreciated 👍

_Originally posted by @Demonicious in https://github.com/directus/directus/discussions/2831_

**Comment by cliqer** [comment]
@Demonicious can you please elaborate on how you solved this and what was the problem?
