### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fd' of undefined

### ISSUE THREAD

**Issue by kjj77** [directus/sdk-js#56]
Hi,

I'm trying to use the node module of this SDK in a web app. 
While using Webpack to test the app locally, I can compile but I stumble on this error in console :

-----------
Uncaught TypeError: Cannot read property 'fd' of undefined
-----------

when I try to import with this:

-----------
import { RemoteInstance } from '@directus/sdk-js';
-----------

The complete error is here :

-----------
Uncaught TypeError: Cannot read property 'fd' of undefined
    at Function.t.useColors (remote.umd.js:3951)
    at r (remote.umd.js:3802)
    at eval (remote.umd.js:3985)
    at eval (remote.umd.js:4)
    at Object.eval (remote.umd.js:8)
    at eval (remote.umd.js:7409)
    at Object../node_modules/@directus/sdk-js/dist/remote.umd.js (app.js:804)
    at __webpack_require__ (app.js:725)
    at fn (app.js:102)
    at eval (app.js:12)
-----------

The line is : 

-----------
return "colors" in t.inspectOpts ? Boolean(t.inspectOpts.colors) : qi.isatty(N.stderr.fd);
-----------

I guess it might have to do with the way the module is imported, but since I'm pretty new to webpack I don't know exactly and since it compiles I'm not sure it's not another kind of problem altogether.

I found similarity to this issue related to useColors :

-----------
https://github.com/visionmedia/debug/issues/511
-----------

Any help would be great ! Thanks

**Comment by rijkvanzanten** [comment]
Hey @kjj77! 

Your import seems to be wrong

```js
import { RemoteInstance } from '@directus/sdk-js';
```

should be

```js
import remote from "@directus/sdk-js";
```

**Comment by kjj77** [comment]
Hi and thanks, but I still get the same exact error.
If you want to reproduce it, you can clone this repo:

https://github.com/framework7io/framework7-template-vue-webpack

npm install it to add dependencies, npm install directus-sdk and just add :

          resolvePath('node_modules/@directus/sdk-js')

in build/webpack.config.dev.js (line 51)

and

           import remote from "@directus/sdk-js"; 

in www/app.js (around line 20)

This is enough to trigger the error in console when you launch the app with:

npm run dev

**Comment by rijkvanzanten** [comment]
Oh no! Thanks for giving me a specific case to reproduce with 🙂

We're using this exact SDK in the main Directus app which also used webpack to bundle to code so I'm curious to see what is happening here.

**Comment by honzabilek4** [comment]
Hey, 
I'm also curious about this one, since I prepared the rollup bundles here. 👀 📦 
@rijkvanzanten  keep me posted please 🤓 
Thanks!

**Comment by honzabilek4** [comment]
Hi,
I've run into the same issue in one of our projects. I've solved it temporarily by explicitly including the `esm` bundle, but I'm going to investigate this further.
