### ISSUE TITLE
Typo in SDK contructor in index.js

### ISSUE THREAD

**Issue by dereksx** [directus/sdk-js#58]
Line 62, it should be "project = option.project"?

![image](https://user-images.githubusercontent.com/15847614/50806058-14cf5200-1330-11e9-9742-87b27dfb341e.png)

**Comment by rijkvanzanten** [comment]
> should be "project = option.project"

Yep! Or rather options (plural) 😊

Do you mind opening a PR?

**Comment by rijkvanzanten** [comment]
This is fixed by https://github.com/directus/sdk-js/pull/59
