### ISSUE TITLE
Login with static token

### ISSUE THREAD

**Issue by Niekvan** [directus/sdk-js#61]
When initializing the SDK with the static token an TypeError: Cannot read property 'replace' of undefined is returned.

Reproduce:
1. Add SDK to nuxt.js project
2. Import SDK and initialize client with url, project and token.

login with client.login() works fine.
GET http://localhost/_/users?access_token=admin_token returns the user

**Comment by rijkvanzanten** [comment]
Hey Niek! Could you provide a code example of how you try initializing the SDK?

**Comment by Niekvan** [comment]
I follow the example from the SDK documentation

`import SDK from '@directus/sdk-js`

`const client = new SDK({
url: 'http://localhost/api/public/',
project: '_',
token: 'admin_token'
})`

**Comment by Niekvan** [comment]
Maybe important to add, everything works fine until I add the token. It looks like it fails at the token validation
