### ISSUE TITLE
Javascript does not recognize plain text of ping response

### ISSUE THREAD

**Issue by reitsma** [directus/sdk-js#62]
The ping rest call returns a text string 'pong', as stated in the API Reference documentation. The content-type reported is wrong, it should be text/plain. 

The javascript SDK assumes anything not being an object is JSON. It cannot handle the ping response and returns an error about the invalid JSON. Perhaps a content-type header should be respected.

Version v7.0.15 / API 2.0.15

**Comment by yarick2000** [comment]
Hi, the bug need to be reopen, since the fix (https://github.com/directus/sdk-js/commit/6b1d722e2b79f8d940c335657f69cd9f985f5d85) was not completely correct. There is a missed parameter (headers) in the call of 'request' function. It should be added in order to remove the default value (false) for the new 'ignoreJson' parameter.

**Comment by yarick2000** [comment]
UPDATE: I was trying to replace ping with my own function:
    ping() {
        return this.sdk.request("get", "/server/ping", {}, {}, true, {}, true);
    }
But still was getting the following error:
![image](https://user-images.githubusercontent.com/13006578/60044476-72fab200-9690-11e9-8038-418dc2e380f9.png)
So it can be not enough just to fix params, but may be there is a problem with the logic as well...

**Comment by janbiasi** [comment]
Well for me it works when I override the method, see [this stackblitz example](https://stackblitz.com/edit/directus-issue-62?file=index.ts) ... 

The fix is also included within the next release, see: https://github.com/directus/sdk-js/blob/8568e609078ba9cd8c6e441b36e2bafabc11eab1/src/SDK.ts#L1015
