### ISSUE TITLE
Password reset request going to wrong endpoint.

### ISSUE THREAD

**Issue by Mozz4rt** [directus/sdk-js#63]
Hello, using `client.requestPasswordReset("admin@example.com");`, it sends a POST request to **/auth/reset-request**. I'm guessing that the correct endpoint would be **/auth/password/request**?

**Comment by rijkvanzanten** [comment]
You're right, it should be `/auth/password/request` ([docs](https://docs.directus.io/api/reference.html#password-reset-request))

**Comment by rijkvanzanten** [comment]
This was published on `nom` in `@directus/sdk-js@5.2.1`
