### ISSUE TITLE
How to connect without login ?

### ISSUE THREAD

**Issue by luglio7** [directus/sdk-js#66]
In the documentation is stated that i'm not required to login for public endpoints. but how this can be done with the sdk ?

**Comment by rijkvanzanten** [comment]
You can pass the API URL you want to use in the constructor of the SDK:

```js
import DirectusSDK from "@directus/sdk-js";

const client = new DirectusSDK({
  url: "https://demo-api.directus.app/",
  project: "_",
});

client.getItems("movies")
  .then(console.log);
```
