### ISSUE TITLE
Why `node` in package.json?

### ISSUE THREAD

**Issue by mvhirsch** [directus/sdk-js#73]
Hi!

I have a question: why is there `node` specified in _package.json_? 
I can't see any purpose of this, but it breaks my code because of a other dependency I'm using, which itself compiles against the _^11_ version of node, specified in this package.json (but my local installed version is currently _^10_, because of LTS).

Is there any reason I've overseen for specifying node here? Can we remove it?

Greets from Austria,
Michael

**Comment by rijkvanzanten** [comment]
Hey there!

It was added in during the TypeScript types PR. I don't think it's needed though.

@janbiasi @jlalvarez18 any thoughts?

**Comment by janbiasi** [comment]
I've already pulled it out on my PR, it isn't needed at all.

**Comment by sarneeh** [comment]
This actually breaks my app on a `freebsd` environment, as `npm` is trying to build node from scratch.

**Comment by mvhirsch** [comment]
@janbiasi @rijkvanzanten I've create a PR, since it breaks multiple installations and seems not to be needed. Can you please merge this an create a bugfix release, so we can use it instead? :-)

**Comment by rijkvanzanten** [comment]
Absolutely, I'll release it right away

**Comment by mvhirsch** [comment]
Awesome, thank you very much!

**Comment by rijkvanzanten** [comment]
Published `@directus/sdk-js@5.3.1`
