### ISSUE TITLE
Not token after login

### ISSUE THREAD

**Issue by zappatero** [directus/sdk-js#76]
I use Directus SDK with nuxt. However, after login I do not have the token in the store. The login works fine, as I can see the authentication from axios in the Directus Activity Log. Are there any downgrades in the SDK when it comes to nuxt or do I have it integrated in the wrong way?

Plugin file: directus.js
---
import DirectusSDK from "@directus/sdk-js";
const client = new DirectusSDK();
client.login({
    url: "https://MYURL",
    project: "_",
    email: "admin@example.com",
    password: "password"
});
export default client;

---

**Comment by rijkvanzanten** [comment]
The login call is asynchronous so you're exporting the client before the login is done.

**Comment by zappatero** [comment]
Thanks for your fast reply. I got the point. Just don't know how to solve this. But I will figure it out.

**Comment by rijkvanzanten** [comment]
You can have an async function that resolves with the client whenever the user is logged in. If this is public data, you could also make the data accessible from the public role and skip the login step all together
