### ISSUE TITLE
uploadFiles does not work using NodeJS (plus fix)

### ISSUE THREAD

**Issue by lgersman** [directus/sdk-js#78]
Hi,

at first : great job, guys - i love Directus, thumbs up !!

I am working successfully with the Directus SDK on NodeJS. 

Now i recognized a bug using the uploadFiles function of the SDK using NodeJS (havent tried this function in the browser yet, but i can imagine its the same problem there). 
The SDK sets `"Content-Type": "multipart/form-data"` (see https://github.com/directus/sdk-js/blob/238579c56b53445b67a9153fab8897fed7d684db/src/index.js#L800) for uploading files.

That approach does'nt work.

Instead, it should add the headers from the FormData object.

My current (working!) workaround is overwriting the (not working) directus js sdk function 'uploadFiles' function with my own.

condensed snippet of my working uploadFiles version:

```




import FormData from 'form-data';
import DirectusSDK from '@directus/sdk-js';
...

const directusClient = new DirectusSDK();

...

directusClient.uploadFiles = function(formData, onUploadProgress = () => {}) {
  const headers = {
    // CHANGED : commented out from directus sdk : 
    // "Content-Type": "multipart/form-data",
    // CHANGED : line below added to make file uploads working 
    ...formData.getHeaders(),

    Authorization: `Bearer ${this.token}`,
  };
  // all below is identical to original uploadFiles from directus sdk (see https://github.com/directus/sdk-js/blob/238579c56b53445b67a9153fab8897fed7d684db/src/index.js#L798)
  return this.axios
  .post(`${this.url}/${this.project}/files`, formData, {
    headers,
    onUploadProgress
  })
  .then(res => res.data)
  .catch(error => {
    if (error.response) {
      throw error.response.data.error;
    } else {
      throw {
        // eslint-disable-line
        code: -1,
        message: "Network Error",
        error
      };
    }
  });
};

...

const formData = new FormData();
formData.append('foo.pdf', fs.readFileSync('foo.pdf'), 'foo.pdf');
formData.append('bar.jpg', fs.readFileSync('bar.jpg'), 'bar.jpg');

const attachments = await directusClient.uploadFiles(formData);
// TADA - it just works !!
```

Hope you guys may fix that :-)

**Comment by janbiasi** [comment]
Well, MDN and TypeScript told me that the method `getHeaders` does not exist on the `FormData` object (see spec on https://developer.mozilla.org/de/docs/Web/API/FormData), there's also still an [open discussion](https://github.com/form-data/form-data/issues/369#issuecomment-325164921) since 2017 on the `form-data` library as they also told that this isn't meant to use in your own code.

In my opinion we shouldn't invoke a simple `...(formData.getHeaders() || {})` as it would be an un-needed overhead and third-party library specific, but I think we could provide an option for setting additional headers.

I wouldn't consider this as a bug, it's more an incompatibility with the [form-data](https://github.com/form-data/form-data) library.

What do you think @rijkvanzanten ?
cc @lgersman

**Comment by lgersman** [comment]
Hi guys,

i've tried both snippets but none of them worked using NodeJS/form-data.

How about that snippet ? 

````
import FormData from 'form-data';
import DirectusSDK from '@directus/sdk-js';

const directusClient = new DirectusSDK();

directusClient.uploadFiles = function(formData, onUploadProgress = () => {}) {
  const headers = {
    ...(formData.getHeaders ? formData.getHeaders() : { 'Content-Type': 'multipart/form-data' }),
    Authorization: `Bearer ${this.token}`,
  };
};
````

It works for both form-data (function `getHeaders` exists and will be called) otherwise the default `{ 'Content-Type': 'multipart/form-data' }` will be applied.

Works fine for me.

**Comment by rijkvanzanten** [comment]
I know that `multipart/form-data` works as expected in the browser. What is the output of `formData.getHeaders()` in this case? Wondering what it adds that isn't there right now

**Comment by lgersman** [comment]
formData.getHeaders() => 
````
{
  "content-type": "multipart/form-data; boundary=--------------------------693343438674222528347432"
}
````

**Comment by rijkvanzanten** [comment]
I can confirm that the browser is overriding this header:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/9141017/61223906-98a53500-a6eb-11e9-9e06-9acfcdadaafd.png">

By setting it ourselves, I'm guessing Axios in Node doesn't override the header correctly, but does in the browser somehow. 

What happens if we remove that header completely?

**Comment by rijkvanzanten** [comment]
@janbiasi It does explain why your custom `boundary=-----0000000000000` didn't work, as it's a special boundary generated by the form-data library

**Comment by rijkvanzanten** [comment]
> I've borrowed my solution from this axios issue : axios/axios#1006 (comment)

Yeah.. the tricky bit is that `.getHeaders()` is an internal API not meant for in-app use. Seeing that it doesn't exist on the browser native FormData, I think we should opt for a solution that doesn't rely on it if possible. @lgersman

**Comment by lgersman** [comment]
> I can confirm that the browser is overriding this header:
> 
> <img alt="image" width="572" src="https://user-images.githubusercontent.com/9141017/61223906-98a53500-a6eb-11e9-9e06-9acfcdadaafd.png">
> 
> By setting it ourselves, I'm guessing Axios in Node doesn't override the header correctly, but does in the browser somehow.
> 
> What happens if we remove that header completely?

It doesnt work without setting the header : 

````
'data: This value should not be blank. filename: This value should not be blank.'
````

**Comment by lgersman** [comment]
> > I've borrowed my solution from this axios issue : [axios/axios#1006](https://github.com/axios/axios/issues/1006) (comment)
> 
> Yeah.. the tricky bit is that `.getHeaders()` is an internal API not meant for in-app use. Seeing that it doesn't exist on the browser native FormData, I think we should opt for a solution that doesn't rely on it if possible. @lgersman

If you can provide another solution running in NodeJS without using `formData.getHeaders()` - well, will be fine for me.

**Comment by rijkvanzanten** [comment]
I'm baffled as to why Axios would override / append this header in the browser, as demonstrated above, but not in Node 🤔

**Comment by lgersman** [comment]
> I'm baffled as to why Axios would override / append this header in the browser, as demonstrated above, but not in Node

Yeah, 588 open bugs should result in a *blinking red warning sign* for a simple "Promise based HTTP client for the browser and node.js" library ... i personally prefer Got for NodeJS (https://github.com/sindresorhus/got) / Ky for Browser (https://github.com/sindresorhus/ky) but there is now other good solution working on both sides ...

**Comment by rijkvanzanten** [comment]
Nah that's an unfair comparison. Axios is _by far_ the most used http request library out there. The next big option would be `request`, which at roughly a third of the stars has a third of the open issues as well. Besides, the author(s) of Axios decided to leave all the feature requests open as well, which further increases the optical illusion. (Compare that to a repo where they close everything that isn't a confirmed bug like [`lodash`](https://github.com/lodash/lodash))

**Comment by lgersman** [comment]
> Nah that's an unfair comparison. Axios is _by far_ the most used http request library out there. The next big option would be `request`, which at roughly a third of the stars has a third of the open issues as well. Besides, the author(s) of Axios decided to leave all the feature requests open as well, which further increases the optical illusion. (Compare that to a repo where they close everything that isn't a confirmed bug like [`lodash`](https://github.com/lodash/lodash))

As I said "but there is no other good solution working on both sides" which implicates "it is a good solution" ;-)

**Comment by rijkvanzanten** [comment]
Just sayin' that the number of open issues on a GitHub repo doesn't necessarily mean anything concrete 🙂

**Comment by janbiasi** [comment]
> Just sayin' that the number of open issues on a GitHub repo doesn't necessarily mean anything concrete 🙂

I think this says much more about axios than open issues ;) React or Angular do have about the same amount of open issues, which literally tells nothing about the lib/framework itself.

![image](https://user-images.githubusercontent.com/4563751/61245206-434d4000-a74c-11e9-933c-0d350df200ee.png)

> It works for form-data (function getHeaders exists and will be called) and otherwise the default { 'Content-Type': 'multipart/form-data' } will be applied.
Works fine for me.

Works for the case if you're using the `form-data` framework, but an SDK should never rely on any third-party frameworks as Rijk already stated.

You've provided the GitHub issue with information about that, there's also a workaround which should work (see https://github.com/axios/axios/issues/1006#issuecomment-390935872) 

```js
const querystring = require('querystring')
axios
  .post(URL, querystring.stringify(data))
  .then((response) => ...)
  .catch((error) => ...)
```

However, I'll create a PR which enables you to override headers for any case of using `framework-xyz` just to make sure you have the options to override headers.

Please check the provided solution from axios itself first, thanks!
cc @lgersman

**Comment by lgersman** [comment]
> > Just sayin' that the number of open issues on a GitHub repo doesn't necessarily mean anything concrete slightly_smiling_face
> 
> I think this says much more about axios than open issues ;) React or Angular do have about the same amount of open issues, which literally tells nothing about the lib/framework itself.
> 
> ![image](https://user-images.githubusercontent.com/4563751/61245206-434d4000-a74c-11e9-933c-0d350df200ee.png)
> 
> > It works for form-data (function getHeaders exists and will be called) and otherwise the default { 'Content-Type': 'multipart/form-data' } will be applied.
> > Works fine for me.
> 
> Works for the case if you're using the `form-data` framework, but an SDK should never rely on any third-party frameworks as Rijk already stated. I also found the corresponding code for this behaviour in [lib/defaults.js#L35-L41](https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L35-L41) so it seems that axios won't transform Buffer, Streams or similar.
> 
> You've provided the GitHub issue with information about that, there's also a workaround which should work (see [axios/axios#1006 (comment)](https://github.com/axios/axios/issues/1006#issuecomment-390935872)):
> 
> ```js
> const querystring = require('querystring')
> axios
>   .post(URL, querystring.stringify(data))
>   .then((response) => ...)
>   .catch((error) => ...)
> ```
> 
> However, I'll create a PR which enables you to override headers for any case of using `framework-xyz` just to make sure you have the options to override headers.

Agreed.

> 
> Please check the provided solution from axios itself first, thanks!
> cc @lgersman

Dont't get me wrong but converting form data using querystring doesnt help me out when trying to upload files. 

Anyway, the proposed solution by providing additional headers to the uploadFiles function is what I need. 

Great work, guys !!

**Comment by dgram** [comment]
can it be that the current version of directus-sdk (6) have the same problem?

i can't upload files, i always get an error

```
 Missing boundary in multipart/form-data POST data in <b>Unknown</b>
```

the code looks something like this
```ts
import * as FormData from 'form-data';
import SDK from '@directus/sdk-js';

const sdk = new SDK({});
let data = new FormData();
data.append('file', image.content, image.filename);

try {               
    let upload = await sdk.uploadFiles(data);
} catch (e) {
    console.log(e)
}
````

**Comment by rijkvanzanten** [comment]
@dgram could you open a new issue for that
