### ISSUE TITLE
Error logging in to Directus

### ISSUE THREAD

**Issue by visualcookie** [directus/sdk-js#80]
Hey.

I currently have the problem, that I can't log in to Directus via a source plugin for Gatsby. This issue only occurs on Heroku, when running normally on `localhost` there are no issues whatsoever.

I've posted an initial issue on the source plugins issue board, but I'm thinking this could be an issue with the SDK, since this plugin is using the SDK correctly (from my POV).

Here the initial issue: https://github.com/Jonesus/gatsby-source-directus7/issues/14

**Comment by rijkvanzanten** [comment]
I don't think this is an issue in the SDK itself.. The login method does exactly what it needs to do. Based on the error you get (Method not allowed) it looks like the SDK is trying to hit the wrong endpoint. Could you make sure you used the right URL and project when initializing the SDK? If you used environment variables for these on Heroku, please make sure they're correct.

**Comment by rijkvanzanten** [comment]
I'll close this issue as the login method in the SDK itself works as expected
