### ISSUE TITLE
Remove argument validation strategy

### ISSUE THREAD

**Issue by janbiasi** [directus/sdk-js#92]
# 🚀 feature request

### Description
The argument validation takes about ~100LoC (source & compiled) for the implementation and requires invariation / runtime type checking services with another ~50LoC (source) / ~80LoC (compiled) which isn't just nothing.

### Describe the solution you'd like
~~We need to talk about if the whole strategy makes sense in todays world and/or if we could find a neat solution for that (eg. with TS decorators or [metadata reflection](https://www.npmjs.com/package/reflect-metadata) which wouldn't affect runtime code / bundle size a lot).~~
Remove the whole argument validation stack and just propose a better/solid error message to the user eg:

`Error while calling <method> <url> <params?>: <thrown Error>` instead of `<thrown Error>`.

**Comment by rijkvanzanten** [comment]
We have every method (including examples) in the docs. I wouldn't mind 🔥 it

**Comment by janbiasi** [comment]
That's what I wanted to hear!
